# Generated by Django 3.2 on 2021-04-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
