# Generated by Django 3.2 on 2021-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
