# Generated by Django 3.2 on 2021-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
